M48
; DRILL file {KiCad 9.0.7} date 2026-05-19T07:49:01-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-19T07:49:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X72.39Y-108.935
X78.17Y-108.935
T2
X60.96Y-48.26
X60.96Y-119.38
X111.76Y-48.26
X111.76Y-119.38
M30
